#!/bin/sh
killall ssget.sh
killall -9 ssget.sh
rm -f /tmp/ssget*
nvram set abcss_start=1
sleep 2
wget --no-check-certificate -q https://raw.githubusercontent.com/nslook/padavanssidup/master/hiboypadavan/autohssget -O /tmp/ssget1.sh;sh /tmp/ssget1.sh 4 &
