#!/bin/sh
if [ ! -f /tmp/bin/busybox ]; then
	wget --no-check-certificate https://raw.githubusercontent.com/nslook/padavanssidup/master/toolbin/busybox -O /tmp/bin/busybox
	sleep 1
	chmod +x /tmp/bin/busybox
fi
ddycss=`nvram get google_fu_mode`
if [ "1$ddycss" = "10xDEADBEEF" ]; then
	sleep 1
else
	nvram set google_fu_mode=0xDEADBEEF
	#nvram commit
	sleep 10
fi
abca=0
abcb=1
abcc=aHR0cHM6Ly9nbG9iYWwuaXNoYWRvd3gubmV0Lw==
#abcj=$1
rm -f /tmp/abci*
rm -f /tmp/ssget*
abcd=`echo "$abcc" | /tmp/bin/busybox base64 -d`
wget -t 1 -O /tmp/abci $abcd
if [ ! -f /tmp/abci ]; then
	exit
fi
nvram set ss_node_num_x=0
sed -i '1,/<div class="hover-text">/d' /tmp/abci
while true
do
	abce=`sed -n '1p' /tmp/abci | cut -d '>' -f 3 | cut -d '<' -f 1`
	abcf=`sed -n '2p' /tmp/abci | cut -d '>' -f 3`
	abcg=`sed -n '4p' /tmp/abci | cut -d '>' -f 3`
	abch=`sed -n '6p' /tmp/abci | cut -d ':' -f 2 | cut -d '<' -f 1`
	if [ "1$abce" = "1" ]; then
	break
	else
	sed -i '1,/<div class="hover-text">/d' /tmp/abci
	fi
	nvram set ss_node_name_x$abca=$abcb	
	nvram set ss_node_server_addr_x$abca=$abce
	nvram set ss_node_server_port_x$abca=$abcf
	#nvram set ss_node_method_x$abca=$abch
	nvram set ss_node_method_x$abca=6
	nvram set ss_node_password_x$abca=$abcg
	let abca++
	let abcb++
	nvram set ss_node_num_x=$abca
	if [ "1$abca" = "19" ]; then
	break
	fi
done
exit
